<a href="https://colab.research.google.com/github/chris-crook/new_python_projects/blob/main/numpy_lecture_2023_1_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [45]:
numbers_list = [5, 9, 15, 25, 40]
numbers_list

[5, 9, 15, 25, 40]

In [46]:
np.array(numbers_list)

array([ 5,  9, 15, 25, 40])

In [96]:
numbers_list / 3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [49]:
numbers_array = np.array(numbers_list)
numbers_array

array([ 5,  9, 15, 25, 40])

In [98]:
numbers_array * 4

array([ 20,  36,  60, 100, 160])

In [52]:
numbers_array % 3

array([2, 0, 0, 1, 1])

In [54]:
new_list = []
for x in numbers_list:
  y = x / 3
  new_list.append(y)


In [55]:
new_list

[1.6666666666666667, 3.0, 5.0, 8.333333333333334, 13.333333333333334]

In [56]:
numbers_array.reshape(-1, 1)

array([[ 5],
       [ 9],
       [15],
       [25],
       [40]])

In [58]:
df = np.array([[1, 2, 3], [4, 5, 6]])

In [60]:
df

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
import pandas as pd
pd.DataFrame(df)

0  1  2
0  1  2  3
1  4  5  6

In [64]:
np.linspace(0, 20, 20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [65]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
np.random.random()

0.3921175181941505

In [81]:
np.random.random() * 10

2.8613933495037944

In [82]:
numbers_array

array([ 5,  9, 15, 25, 40])

In [83]:
numbers_array.argmin()

0

In [84]:
numbers_array[0]

5

In [85]:
numbers_array.argmax()

4

In [86]:
numbers_array[4]

40

In [87]:
numbers_array

array([ 5,  9, 15, 25, 40])

In [88]:
np.where(numbers_array > 12, 'big', 'small')

array(['small', 'small', 'big', 'big', 'big'], dtype='<U5')

In [89]:
import pandas as pd

In [90]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [92]:
np.where(df['Age'] > 50, 'old', np.where(df['Age'] > 25, 'middle age', 'young'))

array(['young', 'middle age', 'middle age', 'middle age', 'middle age',
       'young', 'old', 'young', 'middle age', 'young', 'young', 'old',
       'young', 'middle age', 'young', 'old', 'young', 'young',
       'middle age', 'young', 'middle age', 'middle age', 'young',
       'middle age', 'young', 'middle age', 'young', 'young', 'young',
       'young', 'middle age', 'young', 'young', 'old', 'middle age',
       'middle age', 'young', 'young', 'young', 'young', 'middle age',
       'middle age', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'middle age', 'middle age',
       'old', 'young', 'young', 'middle age', 'young', 'young', 'young',
       'middle age', 'middle age', 'young', 'young', 'young',
       'middle age', 'young', 'young', 'middle age', 'middle age',
       'young', 'young', 'middle age', 'middle age', 'young', 'young',
       'young', 'young', 'middle age', 'young', 'middle age', 'young',
       'middle age', 'you

In [93]:
df['Age Group'] = np.where(df['Age'] > 50, 'old', np.where(df['Age'] > 25, 'middle age', 'young'))

In [94]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   Age Group  
0      0         A/5 21171   7.2500   NaN        S       young  
1      0          PC 17599  71.2833   C85        C  middle age  
2      0  STON/O2. 3101282   7.9250   NaN        S  middle age  
3      0            113803  53.1000  C123        S  middle age  
4      0            373450   8.0500   NaN        S  middle age

In [95]:
np.mean(numbers_array)

18.8